#include "commit0_stub.h"
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

#include "../cJSON.h"

int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size); /* required by C89 */

int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("LLVMFuzzerTestOneInput");
}

#ifdef __cplusplus
}
#endif

