#include "commit0_stub.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size); /* required by C89 */

/* fuzz target entry point, works without libFuzzer */

int main(int argc, char **argv)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("main");
}
