#include "commit0_stub.h"
/*
  Copyright (c) 2009-2017 Dave Gamble and cJSON contributors

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/

/* cJSON */
/* JSON parser in C. */

/* disable warnings about old C89 functions in MSVC */
#if !defined(_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER)
#define _CRT_SECURE_NO_DEPRECATE
#endif

#ifdef __GNUC__
#pragma GCC visibility push(default)
#endif
#if defined(_MSC_VER)
#pragma warning (push)
/* disable warning about single line comments in system headers */
#pragma warning (disable : 4001)
#endif

#include <string.h>
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <limits.h>
#include <ctype.h>
#include <float.h>

#ifdef ENABLE_LOCALES
#include <locale.h>
#endif

#if defined(_MSC_VER)
#pragma warning (pop)
#endif
#ifdef __GNUC__
#pragma GCC visibility pop
#endif

#include "cJSON.h"

/* define our own boolean type */
#ifdef true
#undef true
#endif
#define true ((cJSON_bool)1)

#ifdef false
#undef false
#endif
#define false ((cJSON_bool)0)

/* define isnan and isinf for ANSI C, if in C99 or above, isnan and isinf has been defined in math.h */
#ifndef isinf
#define isinf(d) (isnan((d - d)) && !isnan(d))
#endif
#ifndef isnan
#define isnan(d) (d != d)
#endif

#ifndef NAN
#ifdef _WIN32
#define NAN sqrt(-1.0)
#else
#define NAN 0.0/0.0
#endif
#endif

typedef struct {
    const unsigned char *json;
    size_t position;
} error;
static error global_error = { NULL, 0 };

CJSON_PUBLIC(const char *) cJSON_GetErrorPtr(void)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_GetErrorPtr");
}

CJSON_PUBLIC(char *) cJSON_GetStringValue(const cJSON * const item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_GetStringValue");
}

CJSON_PUBLIC(double) cJSON_GetNumberValue(const cJSON * const item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_GetNumberValue");
}

/* This is a safeguard to prevent copy-pasters from using incompatible C and header files */
#if (CJSON_VERSION_MAJOR != 1) || (CJSON_VERSION_MINOR != 7) || (CJSON_VERSION_PATCH != 19)
    #error cJSON.h and cJSON.c have different versions. Make sure that both have the same.
#endif

CJSON_PUBLIC(const char*) cJSON_Version(void)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_Version");
}

/* Case insensitive string comparison, doesn't consider two NULL pointers equal though */
static int case_insensitive_strcmp(const unsigned char *string1, const unsigned char *string2)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("case_insensitive_strcmp");
}

typedef struct internal_hooks
{
    void *(CJSON_CDECL *allocate)(size_t size);
    void (CJSON_CDECL *deallocate)(void *pointer);
    void *(CJSON_CDECL *reallocate)(void *pointer, size_t size);
} internal_hooks;

#if defined(_MSC_VER)
/* work around MSVC error C2322: '...' address of dllimport '...' is not static */
static void * CJSON_CDECL internal_malloc(size_t size)
{
    return malloc(size);
}
static void CJSON_CDECL internal_free(void *pointer)
{
    free(pointer);
}
static void * CJSON_CDECL internal_realloc(void *pointer, size_t size)
{
    return realloc(pointer, size);
}
#else
#define internal_malloc malloc
#define internal_free free
#define internal_realloc realloc
#endif

/* strlen of character literals resolved at compile time */
#define static_strlen(string_literal) (sizeof(string_literal) - sizeof(""))

static internal_hooks global_hooks = { internal_malloc, internal_free, internal_realloc };

static unsigned char* cJSON_strdup(const unsigned char* string, const internal_hooks * const hooks)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_strdup");
}

CJSON_PUBLIC(void) cJSON_InitHooks(cJSON_Hooks* hooks)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_InitHooks");
}

/* Internal constructor. */
static cJSON *cJSON_New_Item(const internal_hooks * const hooks)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_New_Item");
}

/* Delete a cJSON structure. */
CJSON_PUBLIC(void) cJSON_Delete(cJSON *item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_Delete");
}

/* get the decimal point character of the current locale */
static unsigned char get_decimal_point(void)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("get_decimal_point");
}

typedef struct
{
    const unsigned char *content;
    size_t length;
    size_t offset;
    size_t depth; /* How deeply nested (in arrays/objects) is the input at the current offset. */
    internal_hooks hooks;
} parse_buffer;

/* check if the given size is left to read in a given parse buffer (starting with 1) */
#define can_read(buffer, size) ((buffer != NULL) && (((buffer)->offset + size) <= (buffer)->length))
/* check if the buffer can be accessed at the given index (starting with 0) */
#define can_access_at_index(buffer, index) ((buffer != NULL) && (((buffer)->offset + index) < (buffer)->length))
#define cannot_access_at_index(buffer, index) (!can_access_at_index(buffer, index))
/* get a pointer to the buffer at the position */
#define buffer_at_offset(buffer) ((buffer)->content + (buffer)->offset)

/* Parse the input text to generate a number, and populate the result into item. */
static cJSON_bool parse_number(cJSON * const item, parse_buffer * const input_buffer)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("parse_number");
}

/* don't ask me, but the original cJSON_SetNumberValue returns an integer or double */
CJSON_PUBLIC(double) cJSON_SetNumberHelper(cJSON *object, double number)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_SetNumberHelper");
}

/* Note: when passing a NULL valuestring, cJSON_SetValuestring treats this as an error and return NULL */
CJSON_PUBLIC(char*) cJSON_SetValuestring(cJSON *object, const char *valuestring)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_SetValuestring");
}

typedef struct
{
    unsigned char *buffer;
    size_t length;
    size_t offset;
    size_t depth; /* current nesting depth (for formatted printing) */
    cJSON_bool noalloc;
    cJSON_bool format; /* is this print a formatted print */
    internal_hooks hooks;
} printbuffer;

/* realloc printbuffer if necessary to have at least "needed" bytes more */
static unsigned char* ensure(printbuffer * const p, size_t needed)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("ensure");
}

/* calculate the new length of the string in a printbuffer and update the offset */
static void update_offset(printbuffer * const buffer)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("update_offset");
}

/* securely comparison of floating-point variables */
static cJSON_bool compare_double(double a, double b)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("compare_double");
}

/* Render the number nicely from the given item into a string. */
static cJSON_bool print_number(const cJSON * const item, printbuffer * const output_buffer)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("print_number");
}

/* parse 4 digit hexadecimal number */
static unsigned parse_hex4(const unsigned char * const input)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("parse_hex4");
}

/* converts a UTF-16 literal to UTF-8
 * A literal can be one or two sequences of the form \uXXXX */
static unsigned char utf16_literal_to_utf8(const unsigned char * const input_pointer, const unsigned char * const input_end, unsigned char **output_pointer)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("utf16_literal_to_utf8");
}

/* Parse the input text into an unescaped cinput, and populate item. */
static cJSON_bool parse_string(cJSON * const item, parse_buffer * const input_buffer)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("parse_string");
}

/* Render the cstring provided to an escaped version that can be printed. */
static cJSON_bool print_string_ptr(const unsigned char * const input, printbuffer * const output_buffer)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("print_string_ptr");
}

/* Invoke print_string_ptr (which is useful) on an item. */
static cJSON_bool print_string(const cJSON * const item, printbuffer * const p)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("print_string");
}

/* Predeclare these prototypes. */
static cJSON_bool parse_value(cJSON * const item, parse_buffer * const input_buffer);
static cJSON_bool print_value(const cJSON * const item, printbuffer * const output_buffer);
static cJSON_bool parse_array(cJSON * const item, parse_buffer * const input_buffer);
static cJSON_bool print_array(const cJSON * const item, printbuffer * const output_buffer);
static cJSON_bool parse_object(cJSON * const item, parse_buffer * const input_buffer);
static cJSON_bool print_object(const cJSON * const item, printbuffer * const output_buffer);

/* Utility to jump whitespace and cr/lf */
static parse_buffer *buffer_skip_whitespace(parse_buffer * const buffer)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("buffer_skip_whitespace");
}

/* skip the UTF-8 BOM (byte order mark) if it is at the beginning of a buffer */
static parse_buffer *skip_utf8_bom(parse_buffer * const buffer)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("skip_utf8_bom");
}

CJSON_PUBLIC(cJSON *) cJSON_ParseWithOpts(const char *value, const char **return_parse_end, cJSON_bool require_null_terminated)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_ParseWithOpts");
}

/* Parse an object - create a new root, and populate. */
CJSON_PUBLIC(cJSON *) cJSON_ParseWithLengthOpts(const char *value, size_t buffer_length, const char **return_parse_end, cJSON_bool require_null_terminated)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_ParseWithLengthOpts");
}

/* Default options for cJSON_Parse */
CJSON_PUBLIC(cJSON *) cJSON_Parse(const char *value)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_Parse");
}

CJSON_PUBLIC(cJSON *) cJSON_ParseWithLength(const char *value, size_t buffer_length)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_ParseWithLength");
}

#define cjson_min(a, b) (((a) < (b)) ? (a) : (b))

static unsigned char *print(const cJSON * const item, cJSON_bool format, const internal_hooks * const hooks)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("print");
}

/* Render a cJSON item/entity/structure to text. */
CJSON_PUBLIC(char *) cJSON_Print(const cJSON *item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_Print");
}

CJSON_PUBLIC(char *) cJSON_PrintUnformatted(const cJSON *item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_PrintUnformatted");
}

CJSON_PUBLIC(char *) cJSON_PrintBuffered(const cJSON *item, int prebuffer, cJSON_bool fmt)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_PrintBuffered");
}

CJSON_PUBLIC(cJSON_bool) cJSON_PrintPreallocated(cJSON *item, char *buffer, const int length, const cJSON_bool format)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_PrintPreallocated");
}

/* Parser core - when encountering text, process appropriately. */
static cJSON_bool parse_value(cJSON * const item, parse_buffer * const input_buffer)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("parse_value");
}

/* Render a value to text. */
static cJSON_bool print_value(const cJSON * const item, printbuffer * const output_buffer)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("print_value");
}

/* Build an array from input text. */
static cJSON_bool parse_array(cJSON * const item, parse_buffer * const input_buffer)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("parse_array");
}

/* Render an array to text */
static cJSON_bool print_array(const cJSON * const item, printbuffer * const output_buffer)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("print_array");
}

/* Build an object from the text. */
static cJSON_bool parse_object(cJSON * const item, parse_buffer * const input_buffer)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("parse_object");
}

/* Render an object to text. */
static cJSON_bool print_object(const cJSON * const item, printbuffer * const output_buffer)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("print_object");
}

/* Get Array size/item / object item. */
CJSON_PUBLIC(int) cJSON_GetArraySize(const cJSON *array)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_GetArraySize");
}

static cJSON* get_array_item(const cJSON *array, size_t index)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("get_array_item");
}

CJSON_PUBLIC(cJSON *) cJSON_GetArrayItem(const cJSON *array, int index)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_GetArrayItem");
}

static cJSON *get_object_item(const cJSON * const object, const char * const name, const cJSON_bool case_sensitive)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("get_object_item");
}

CJSON_PUBLIC(cJSON *) cJSON_GetObjectItem(const cJSON * const object, const char * const string)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_GetObjectItem");
}

CJSON_PUBLIC(cJSON *) cJSON_GetObjectItemCaseSensitive(const cJSON * const object, const char * const string)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_GetObjectItemCaseSensitive");
}

CJSON_PUBLIC(cJSON_bool) cJSON_HasObjectItem(const cJSON *object, const char *string)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_HasObjectItem");
}

/* Utility for array list handling. */
static void suffix_object(cJSON *prev, cJSON *item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("suffix_object");
}

/* Utility for handling references. */
static cJSON *create_reference(const cJSON *item, const internal_hooks * const hooks)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("create_reference");
}

static cJSON_bool add_item_to_array(cJSON *array, cJSON *item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("add_item_to_array");
}

/* Add item to array/object. */
CJSON_PUBLIC(cJSON_bool) cJSON_AddItemToArray(cJSON *array, cJSON *item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_AddItemToArray");
}

#if defined(__clang__) || (defined(__GNUC__)  && ((__GNUC__ > 4) || ((__GNUC__ == 4) && (__GNUC_MINOR__ > 5))))
    #pragma GCC diagnostic push
#endif
#ifdef __GNUC__
#pragma GCC diagnostic ignored "-Wcast-qual"
#endif
/* helper function to cast away const */
static void* cast_away_const(const void* string)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cast_away_const");
}
#if defined(__clang__) || (defined(__GNUC__)  && ((__GNUC__ > 4) || ((__GNUC__ == 4) && (__GNUC_MINOR__ > 5))))
    #pragma GCC diagnostic pop
#endif


static cJSON_bool add_item_to_object(cJSON * const object, const char * const string, cJSON * const item, const internal_hooks * const hooks, const cJSON_bool constant_key)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("add_item_to_object");
}

CJSON_PUBLIC(cJSON_bool) cJSON_AddItemToObject(cJSON *object, const char *string, cJSON *item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_AddItemToObject");
}

/* Add an item to an object with constant string as key */
CJSON_PUBLIC(cJSON_bool) cJSON_AddItemToObjectCS(cJSON *object, const char *string, cJSON *item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_AddItemToObjectCS");
}

CJSON_PUBLIC(cJSON_bool) cJSON_AddItemReferenceToArray(cJSON *array, cJSON *item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_AddItemReferenceToArray");
}

CJSON_PUBLIC(cJSON_bool) cJSON_AddItemReferenceToObject(cJSON *object, const char *string, cJSON *item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_AddItemReferenceToObject");
}

CJSON_PUBLIC(cJSON*) cJSON_AddNullToObject(cJSON * const object, const char * const name)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_AddNullToObject");
}

CJSON_PUBLIC(cJSON*) cJSON_AddTrueToObject(cJSON * const object, const char * const name)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_AddTrueToObject");
}

CJSON_PUBLIC(cJSON*) cJSON_AddFalseToObject(cJSON * const object, const char * const name)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_AddFalseToObject");
}

CJSON_PUBLIC(cJSON*) cJSON_AddBoolToObject(cJSON * const object, const char * const name, const cJSON_bool boolean)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_AddBoolToObject");
}

CJSON_PUBLIC(cJSON*) cJSON_AddNumberToObject(cJSON * const object, const char * const name, const double number)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_AddNumberToObject");
}

CJSON_PUBLIC(cJSON*) cJSON_AddStringToObject(cJSON * const object, const char * const name, const char * const string)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_AddStringToObject");
}

CJSON_PUBLIC(cJSON*) cJSON_AddRawToObject(cJSON * const object, const char * const name, const char * const raw)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_AddRawToObject");
}

CJSON_PUBLIC(cJSON*) cJSON_AddObjectToObject(cJSON * const object, const char * const name)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_AddObjectToObject");
}

CJSON_PUBLIC(cJSON*) cJSON_AddArrayToObject(cJSON * const object, const char * const name)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_AddArrayToObject");
}

CJSON_PUBLIC(cJSON *) cJSON_DetachItemViaPointer(cJSON *parent, cJSON * const item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_DetachItemViaPointer");
}

CJSON_PUBLIC(cJSON *) cJSON_DetachItemFromArray(cJSON *array, int which)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_DetachItemFromArray");
}

CJSON_PUBLIC(void) cJSON_DeleteItemFromArray(cJSON *array, int which)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_DeleteItemFromArray");
}

CJSON_PUBLIC(cJSON *) cJSON_DetachItemFromObject(cJSON *object, const char *string)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_DetachItemFromObject");
}

CJSON_PUBLIC(cJSON *) cJSON_DetachItemFromObjectCaseSensitive(cJSON *object, const char *string)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_DetachItemFromObjectCaseSensitive");
}

CJSON_PUBLIC(void) cJSON_DeleteItemFromObject(cJSON *object, const char *string)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_DeleteItemFromObject");
}

CJSON_PUBLIC(void) cJSON_DeleteItemFromObjectCaseSensitive(cJSON *object, const char *string)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_DeleteItemFromObjectCaseSensitive");
}

/* Replace array/object items with new ones. */
CJSON_PUBLIC(cJSON_bool) cJSON_InsertItemInArray(cJSON *array, int which, cJSON *newitem)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_InsertItemInArray");
}

CJSON_PUBLIC(cJSON_bool) cJSON_ReplaceItemViaPointer(cJSON * const parent, cJSON * const item, cJSON * replacement)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_ReplaceItemViaPointer");
}

CJSON_PUBLIC(cJSON_bool) cJSON_ReplaceItemInArray(cJSON *array, int which, cJSON *newitem)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_ReplaceItemInArray");
}

static cJSON_bool replace_item_in_object(cJSON *object, const char *string, cJSON *replacement, cJSON_bool case_sensitive)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("replace_item_in_object");
}

CJSON_PUBLIC(cJSON_bool) cJSON_ReplaceItemInObject(cJSON *object, const char *string, cJSON *newitem)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_ReplaceItemInObject");
}

CJSON_PUBLIC(cJSON_bool) cJSON_ReplaceItemInObjectCaseSensitive(cJSON *object, const char *string, cJSON *newitem)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_ReplaceItemInObjectCaseSensitive");
}

/* Create basic types: */
CJSON_PUBLIC(cJSON *) cJSON_CreateNull(void)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_CreateNull");
}

CJSON_PUBLIC(cJSON *) cJSON_CreateTrue(void)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_CreateTrue");
}

CJSON_PUBLIC(cJSON *) cJSON_CreateFalse(void)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_CreateFalse");
}

CJSON_PUBLIC(cJSON *) cJSON_CreateBool(cJSON_bool boolean)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_CreateBool");
}

CJSON_PUBLIC(cJSON *) cJSON_CreateNumber(double num)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_CreateNumber");
}

CJSON_PUBLIC(cJSON *) cJSON_CreateString(const char *string)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_CreateString");
}

CJSON_PUBLIC(cJSON *) cJSON_CreateStringReference(const char *string)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_CreateStringReference");
}

CJSON_PUBLIC(cJSON *) cJSON_CreateObjectReference(const cJSON *child)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_CreateObjectReference");
}

CJSON_PUBLIC(cJSON *) cJSON_CreateArrayReference(const cJSON *child) {
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_CreateArrayReference");
}

CJSON_PUBLIC(cJSON *) cJSON_CreateRaw(const char *raw)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_CreateRaw");
}

CJSON_PUBLIC(cJSON *) cJSON_CreateArray(void)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_CreateArray");
}

CJSON_PUBLIC(cJSON *) cJSON_CreateObject(void)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_CreateObject");
}

/* Create Arrays: */
CJSON_PUBLIC(cJSON *) cJSON_CreateIntArray(const int *numbers, int count)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_CreateIntArray");
}

CJSON_PUBLIC(cJSON *) cJSON_CreateFloatArray(const float *numbers, int count)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_CreateFloatArray");
}

CJSON_PUBLIC(cJSON *) cJSON_CreateDoubleArray(const double *numbers, int count)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_CreateDoubleArray");
}

CJSON_PUBLIC(cJSON *) cJSON_CreateStringArray(const char *const *strings, int count)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_CreateStringArray");
}

/* Duplication */
cJSON * cJSON_Duplicate_rec(const cJSON *item, size_t depth, cJSON_bool recurse);

CJSON_PUBLIC(cJSON *) cJSON_Duplicate(const cJSON *item, cJSON_bool recurse)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_Duplicate");
}

cJSON * cJSON_Duplicate_rec(const cJSON *item, size_t depth, cJSON_bool recurse)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_Duplicate_rec");
}

static void skip_oneline_comment(char **input)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("skip_oneline_comment");
}

static void skip_multiline_comment(char **input)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("skip_multiline_comment");
}

static void minify_string(char **input, char **output) {
    /* STUB: generated by cstubber */
    STUB_PANIC("minify_string");
}

CJSON_PUBLIC(void) cJSON_Minify(char *json)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_Minify");
}

CJSON_PUBLIC(cJSON_bool) cJSON_IsInvalid(const cJSON * const item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_IsInvalid");
}

CJSON_PUBLIC(cJSON_bool) cJSON_IsFalse(const cJSON * const item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_IsFalse");
}

CJSON_PUBLIC(cJSON_bool) cJSON_IsTrue(const cJSON * const item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_IsTrue");
}


CJSON_PUBLIC(cJSON_bool) cJSON_IsBool(const cJSON * const item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_IsBool");
}
CJSON_PUBLIC(cJSON_bool) cJSON_IsNull(const cJSON * const item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_IsNull");
}

CJSON_PUBLIC(cJSON_bool) cJSON_IsNumber(const cJSON * const item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_IsNumber");
}

CJSON_PUBLIC(cJSON_bool) cJSON_IsString(const cJSON * const item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_IsString");
}

CJSON_PUBLIC(cJSON_bool) cJSON_IsArray(const cJSON * const item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_IsArray");
}

CJSON_PUBLIC(cJSON_bool) cJSON_IsObject(const cJSON * const item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_IsObject");
}

CJSON_PUBLIC(cJSON_bool) cJSON_IsRaw(const cJSON * const item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_IsRaw");
}

CJSON_PUBLIC(cJSON_bool) cJSON_Compare(const cJSON * const a, const cJSON * const b, const cJSON_bool case_sensitive)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_Compare");
}

CJSON_PUBLIC(void *) cJSON_malloc(size_t size)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_malloc");
}

CJSON_PUBLIC(void) cJSON_free(void *object)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSON_free");
}
