#include "commit0_stub.h"
/*
  Copyright (c) 2009-2017 Dave Gamble and cJSON contributors

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/

/* disable warnings about old C89 functions in MSVC */
#if !defined(_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER)
#define _CRT_SECURE_NO_DEPRECATE
#endif

#ifdef __GNUCC__
#pragma GCC visibility push(default)
#endif
#if defined(_MSC_VER)
#pragma warning (push)
/* disable warning about single line comments in system headers */
#pragma warning (disable : 4001)
#endif

#include <ctype.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <limits.h>
#include <math.h>
#include <float.h>
#include <math.h>

#if defined(_MSC_VER)
#pragma warning (pop)
#endif
#ifdef __GNUCC__
#pragma GCC visibility pop
#endif

#include "cJSON_Utils.h"

/* define our own boolean type */
#ifdef true
#undef true
#endif
#define true ((cJSON_bool)1)

#ifdef false
#undef false
#endif
#define false ((cJSON_bool)0)

static unsigned char* cJSONUtils_strdup(const unsigned char* const string)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSONUtils_strdup");
}

/* string comparison which doesn't consider NULL pointers equal */
static int compare_strings(const unsigned char *string1, const unsigned char *string2, const cJSON_bool case_sensitive)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("compare_strings");
}

/* securely comparison of floating-point variables */
static cJSON_bool compare_double(double a, double b)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("compare_double");
}


/* Compare the next path element of two JSON pointers, two NULL pointers are considered unequal: */
static cJSON_bool compare_pointers(const unsigned char *name, const unsigned char *pointer, const cJSON_bool case_sensitive)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("compare_pointers");
}

/* calculate the length of a string if encoded as JSON pointer with ~0 and ~1 escape sequences */
static size_t pointer_encoded_length(const unsigned char *string)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("pointer_encoded_length");
}

/* copy a string while escaping '~' and '/' with ~0 and ~1 JSON pointer escape codes */
static void encode_string_as_pointer(unsigned char *destination, const unsigned char *source)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("encode_string_as_pointer");
}

CJSON_PUBLIC(char *) cJSONUtils_FindPointerFromObjectTo(const cJSON * const object, const cJSON * const target)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSONUtils_FindPointerFromObjectTo");
}

/* non broken version of cJSON_GetArrayItem */
static cJSON *get_array_item(const cJSON *array, size_t item)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("get_array_item");
}

static cJSON_bool decode_array_index_from_pointer(const unsigned char * const pointer, size_t * const index)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("decode_array_index_from_pointer");
}

static cJSON *get_item_from_pointer(cJSON * const object, const char * pointer, const cJSON_bool case_sensitive)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("get_item_from_pointer");
}

CJSON_PUBLIC(cJSON *) cJSONUtils_GetPointer(cJSON * const object, const char *pointer)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSONUtils_GetPointer");
}

CJSON_PUBLIC(cJSON *) cJSONUtils_GetPointerCaseSensitive(cJSON * const object, const char *pointer)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSONUtils_GetPointerCaseSensitive");
}

/* JSON Patch implementation. */
static void decode_pointer_inplace(unsigned char *string)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("decode_pointer_inplace");
}

/* non-broken cJSON_DetachItemFromArray */
static cJSON *detach_item_from_array(cJSON *array, size_t which)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("detach_item_from_array");
}

/* detach an item at the given path */
static cJSON *detach_path(cJSON *object, const unsigned char *path, const cJSON_bool case_sensitive)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("detach_path");
}

/* sort lists using mergesort */
static cJSON *sort_list(cJSON *list, const cJSON_bool case_sensitive)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("sort_list");
}

static void sort_object(cJSON * const object, const cJSON_bool case_sensitive)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("sort_object");
}

static cJSON_bool compare_json(cJSON *a, cJSON *b, const cJSON_bool case_sensitive)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("compare_json");
}

/* non broken version of cJSON_InsertItemInArray */
static cJSON_bool insert_item_in_array(cJSON *array, size_t which, cJSON *newitem)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("insert_item_in_array");
}

static cJSON *get_object_item(const cJSON * const object, const char* name, const cJSON_bool case_sensitive)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("get_object_item");
}

enum patch_operation { INVALID, ADD, REMOVE, REPLACE, MOVE, COPY, TEST };

static enum patch_operation decode_patch_operation(const cJSON * const patch, const cJSON_bool case_sensitive)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("decode_patch_operation");
}

/* overwrite and existing item with another one and free resources on the way */
static void overwrite_item(cJSON * const root, const cJSON replacement)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("overwrite_item");
}

static int apply_patch(cJSON *object, const cJSON *patch, const cJSON_bool case_sensitive)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("apply_patch");
}

CJSON_PUBLIC(int) cJSONUtils_ApplyPatches(cJSON * const object, const cJSON * const patches)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSONUtils_ApplyPatches");
}

CJSON_PUBLIC(int) cJSONUtils_ApplyPatchesCaseSensitive(cJSON * const object, const cJSON * const patches)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSONUtils_ApplyPatchesCaseSensitive");
}

static void compose_patch(cJSON * const patches, const unsigned char * const operation, const unsigned char * const path, const unsigned char *suffix, const cJSON * const value)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("compose_patch");
}

CJSON_PUBLIC(void) cJSONUtils_AddPatchToArray(cJSON * const array, const char * const operation, const char * const path, const cJSON * const value)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSONUtils_AddPatchToArray");
}

static void create_patches(cJSON * const patches, const unsigned char * const path, cJSON * const from, cJSON * const to, const cJSON_bool case_sensitive)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("create_patches");
}

CJSON_PUBLIC(cJSON *) cJSONUtils_GeneratePatches(cJSON * const from, cJSON * const to)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSONUtils_GeneratePatches");
}

CJSON_PUBLIC(cJSON *) cJSONUtils_GeneratePatchesCaseSensitive(cJSON * const from, cJSON * const to)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSONUtils_GeneratePatchesCaseSensitive");
}

CJSON_PUBLIC(void) cJSONUtils_SortObject(cJSON * const object)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSONUtils_SortObject");
}

CJSON_PUBLIC(void) cJSONUtils_SortObjectCaseSensitive(cJSON * const object)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSONUtils_SortObjectCaseSensitive");
}

static cJSON *merge_patch(cJSON *target, const cJSON * const patch, const cJSON_bool case_sensitive)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("merge_patch");
}

CJSON_PUBLIC(cJSON *) cJSONUtils_MergePatch(cJSON *target, const cJSON * const patch)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSONUtils_MergePatch");
}

CJSON_PUBLIC(cJSON *) cJSONUtils_MergePatchCaseSensitive(cJSON *target, const cJSON * const patch)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSONUtils_MergePatchCaseSensitive");
}

static cJSON *generate_merge_patch(cJSON * const from, cJSON * const to, const cJSON_bool case_sensitive)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("generate_merge_patch");
}

CJSON_PUBLIC(cJSON *) cJSONUtils_GenerateMergePatch(cJSON * const from, cJSON * const to)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSONUtils_GenerateMergePatch");
}

CJSON_PUBLIC(cJSON *) cJSONUtils_GenerateMergePatchCaseSensitive(cJSON * const from, cJSON * const to)
{
    /* STUB: generated by cstubber */
    STUB_PANIC("cJSONUtils_GenerateMergePatchCaseSensitive");
}
